// ── Weekly Report: Generator ─────────────────────────────────────────
//
// Orchestrates data collection, rendering, and storage.

import { randomUUID } from 'crypto';
import path from 'path';
import fs from 'fs';
import { execute, queryOne } from '../db/client';
import { logger } from '../lib/logger';
import {
  collectPortfolioSummary, collectSLASummary, collectBudgetSummary,
  collectHealthSummary, collectMeetingsSummary, collectSyncSummary,
  collectActionItems, collectHighlights,
} from './collector';
import { renderReportHTML, type WeeklyReportData } from './renderer';

function getApp() {
  return require('electron').app as import('electron').App;
}

export interface GenerateReportOptions {
  periodEnd?: Date;
  autoGenerated?: boolean;
}

export function generateWeeklyReport(options?: GenerateReportOptions): string {
  // Calculate period (Monday-Friday)
  const endDate = options?.periodEnd || new Date();
  const dayOfWeek = endDate.getDay(); // 0=Sun, 5=Fri

  const friday = new Date(endDate);
  if (dayOfWeek === 0) {
    friday.setDate(endDate.getDate() - 2); // Sun -> prev Fri
  } else if (dayOfWeek === 6) {
    friday.setDate(endDate.getDate() - 1); // Sat -> prev Fri
  } else if (dayOfWeek < 5) {
    friday.setDate(endDate.getDate() + (5 - dayOfWeek)); // Mon-Thu -> this Fri
  }
  // else dayOfWeek === 5, it's Friday
  friday.setHours(23, 59, 59, 999);

  const monday = new Date(friday);
  monday.setDate(friday.getDate() - 4);
  monday.setHours(0, 0, 0, 0);

  const periodStart = monday.toISOString();
  const periodEnd = friday.toISOString();
  const periodLabel = `${monday.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} — ${friday.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;

  // Collect all data
  const portfolioSummary = collectPortfolioSummary(periodStart, periodEnd);
  const slaSummary = collectSLASummary();
  const budgetSummary = collectBudgetSummary();
  const healthSummary = collectHealthSummary();
  const meetingsSummary = collectMeetingsSummary(periodStart, periodEnd);
  const syncSummary = collectSyncSummary(periodStart, periodEnd);
  const actionItems = collectActionItems(periodStart, periodEnd);
  const highlights = collectHighlights(periodStart, periodEnd);

  const title = `Week of ${periodLabel}`;
  const generatedAt = new Date().toISOString();

  // Render HTML
  const reportData: WeeklyReportData = {
    title, periodLabel, generatedAt,
    portfolioSummary, slaSummary, budgetSummary, healthSummary,
    meetingsSummary, syncSummary, actionItems, highlights,
  };

  const htmlContent = renderReportHTML(reportData);

  // Save to database
  const reportId = randomUUID();
  const reportDate = friday.toISOString().split('T')[0];

  execute(`
    INSERT INTO weekly_reports (
      id, report_date, period_start, period_end, title, generated_at,
      portfolio_summary_json, sla_summary_json, budget_summary_json,
      health_summary_json, sync_summary_json, meetings_summary_json,
      activity_summary_json, action_items_json, highlights_json,
      html_content, auto_generated
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `, [
    reportId,
    reportDate,
    periodStart, periodEnd, title, generatedAt,
    JSON.stringify(portfolioSummary), JSON.stringify(slaSummary),
    JSON.stringify(budgetSummary), JSON.stringify(healthSummary),
    JSON.stringify(syncSummary), JSON.stringify(meetingsSummary),
    '{}', JSON.stringify(actionItems), JSON.stringify(highlights),
    htmlContent,
    options?.autoGenerated ? 1 : 0,
  ]);

  // Save HTML file
  const app = getApp();
  const reportsDir = path.join(app.getPath('userData'), 'data', 'reports');
  fs.mkdirSync(reportsDir, { recursive: true });
  const filename = `ops-report-${reportDate}.html`;
  const filepath = path.join(reportsDir, filename);
  fs.writeFileSync(filepath, htmlContent, 'utf-8');

  execute('UPDATE weekly_reports SET export_path = ? WHERE id = ?', [filepath, reportId]);

  logger.report('Generated', { title, path: filepath });
  return reportId;
}
