import { registerDBHandlers } from './db';
import { registerSettingsHandlers } from './settings';
import { registerSyncHandlers } from './sync';
import { registerSubAccountHandlers } from './subaccounts';
import { registerAssociationHandlers } from './associations';
import { registerQueueHandlers } from './queue';
import { registerRagHandlers } from './rag';
import { registerGdriveHandlers } from './gdrive';
import { registerBriefingHandlers } from './briefing';
import { registerCloudHandlers } from './cloud';
import { registerCalendarHandlers } from './calendar';
import { registerHealthHandlers } from './health';
import { registerReportsHandlers } from './reports';
import { registerKinstaHandlers } from './kinsta';
import { registerNotificationHandlers } from './notifications';
import { registerReadAiAuthHandlers } from './readai-auth';
import { registerReadAiSyncHandlers } from './readai-sync';
import { registerA2PHandlers } from './a2p';
import { registerSEOHandlers } from './seo';
import { registerSuggestionHandlers } from './suggestions';
import { registerGmailHandlers } from './gmail';
import { registerGoogleAccountHandlers } from './google-accounts';

export function registerIPCHandlers(): void {
  registerDBHandlers();
  registerSettingsHandlers();
  registerSyncHandlers();
  registerSubAccountHandlers();
  registerAssociationHandlers();
  registerQueueHandlers();
  registerRagHandlers();
  registerGdriveHandlers();
  registerBriefingHandlers();
  registerCloudHandlers();
  registerCalendarHandlers();
  registerHealthHandlers();
  registerReportsHandlers();
  registerKinstaHandlers();
  registerNotificationHandlers();
  registerReadAiAuthHandlers();
  registerReadAiSyncHandlers();
  registerA2PHandlers();
  registerSEOHandlers();
  registerSuggestionHandlers();
  registerGmailHandlers();
  registerGoogleAccountHandlers();
}
