name = "li-ops-hub-api"
main = "worker/src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "li-ops-hub-cloud"
database_id = "4543ec2e-1cc3-45cf-93c5-77c20af83b2e"
